# -*- coding: utf-8 -*-
"""daily_weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEtzzDVuQ7vJY30pNNHQL70roEEljEip
"""

# Required imports
from datetime import datetime, timedelta, timezone
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt
import boto3
import io
import pendulum

# AWS configuration
BUCKET_NAME = "natarajan-williams-silverman-bucket"
S3_DATA_DIR = "weather_data/"
S3_OUTPUT_DIR = "output_graphs/"
AWS_REGION = "us-east-2"

# Setting up S3 session and client
session = boto3.Session(region_name=AWS_REGION)
s3 = session.client("s3")


# Extracting 24 hours of data and generating visual plots 
def extract_and_plot(**kwargs):
    print("Starting dashboard task...")

    # Getting the current UTC time and computing the cutoff time for 24 hrs ago
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=24)

    # Listing all objects in the specified weather data S3 folder
    response = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix=S3_DATA_DIR)

    # Extracting the list of files
    files = response.get("Contents", [])

    # Filtering files for .csv and were last modified in the last 24 hours 
    recent_files = [
        obj["Key"] for obj in files
        if obj["Key"].endswith(".csv") and obj["LastModified"] >= cutoff
    ]

    print(f"Found {len(recent_files)} recent files:", recent_files)

    # Exiting if no data
    if not recent_files:
        print("No recent weather files found.")
        return

    # Loading all recent CSVs into DFs
    dfs = []
    for file_key in recent_files:
        try:
            # Downloading and reading the file from S3 into a DF
            obj = s3.get_object(Bucket=BUCKET_NAME, Key=file_key)
            df = pd.read_csv(io.BytesIO(obj['Body'].read()))
            dfs.append(df)
        except Exception as e:
            print(f"Failed to read {file_key}: {e}")

    # Exiting if files failed
    if not dfs:
        print("No dataframes could be loaded.")
        return

    # Combining all loaded data
    df_all = pd.concat(dfs, ignore_index=True)
    print(f"Combined DataFrame shape: {df_all.shape}")
    print(df_all.head())

    # Plotting each metric
    # List of metrics to plot
    for metric in ["temperature", "visibility", "relativeHumidity"]:
        # Skipping plot if metric isnt found in data
        if metric not in df_all.columns:
            print(f"Skipping missing metric: {metric}")
            continue
        # Preparing timestamp for x-axis (making sure timestamp col is parsed as datetime format)
        df_all["timestamp"] = pd.to_datetime(df_all["timestamp"])
        plt.figure(figsize=(10, 6))
        # Iterating through each unique weather station
        for station in df_all["station"].dropna().unique():
            # Getting only that stations data
            station_df = df_all[df_all["station"] == station].sort_values("timestamp")
            # Plotting time vs metric value
            plt.plot(station_df["timestamp"], station_df[metric], label=station)

        plt.title(f"{metric} by station")
        plt.xlabel("Time")
        plt.ylabel(metric)
        plt.legend()
        plt.xticks(rotation=45)
        plt.tight_layout()

        # Uploading the plot as a PNG to S3
        # Saving the figure to an in-memory byte buffer
        buffer = io.BytesIO()
        plt.savefig(buffer, format="png")
        buffer.seek(0)
        # Renaming the output file using the metric name and date
        filename = f"{S3_OUTPUT_DIR}{metric}_{now.date()}.png"
        try:
            # uploading the PNG to S3
            s3.upload_fileobj(buffer, BUCKET_NAME, filename)
            print(f"Uploaded {filename} to S3.")
        except Exception as e:
            print(f"Failed to upload {filename}: {e}")
        buffer.close() # freeing memory
        plt.close()

    print("Dashboard plots uploaded.")


    # Defining the Airflow DAG
    with DAG(
    dag_id="daily_weather_dashboard",
    default_args={
        'owner': 'airflow',
        'depends_on_past': False,
        'start_date': pendulum.datetime(2025, 6, 4, 0, 0, 0, tz="UTC"),
        'end_date': pendulum.today('UTC').add(days=1),
        'retries': 1,
        'retry_delay': timedelta(minutes=5)
    },
    description="Generate daily weather plots from S3 CSVs",
    schedule="@daily", # running once per day
    catchup=False, # do not backfill past runs
    tags=["weather", "dashboard"] # organizing in the UI
    ) as dag:

        # Defining task sequence: start --> generate --> end
        start = EmptyOperator(task_id="start")
        make_dashboard = PythonOperator(
            task_id="generate_dashboard",
            python_callable=extract_and_plot
        )
        end = EmptyOperator(task_id="end")

        start >> make_dashboard >> end # task order