# -*- coding: utf-8 -*-
"""weather_data_2hrs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RddZNwJnem-sEsDTmA-2VhLrmPU1a8eG
"""
# Importing DAG structure and Python Operator to define tasks
from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import boto3
from sklearn.linear_model import LinearRegression
import pendulum
import requests
import time
import io

# AWS and file storage config
BUCKET_NAME = "natarajan-williams-silverman-bucket" 
S3_DATA_DIR = "weather_data/" # where observations csvs go   
S3_OUTPUT_DIR = "predictions/"
AWS_REGION = "us-east-2"

# Connecting to S3
session = boto3.Session(region_name=AWS_REGION)
s3 = session.client("s3")


# Uploading a df to S3 as a CSV file
def upload_to_s3(df, key, bucket=BUCKET_NAME):
    import io
    csv_buffer = io.StringIO()
    df.to_csv(csv_buffer, index=False) # writing df to csv
    s3.put_object(Body=csv_buffer.getvalue(), Bucket=bucket, Key=key) # uploading csv to s3
    print(f"Uploaded to s3://{bucket}/{key}")

# Collecting weather data from stations
def collect_weather_data(**kwargs):
    WEATHER_STATIONS = ["KORD", "KENW", "KMDW", "KPNT"]
    BASE_URL = "https://api.weather.gov/stations/{station}/observations/latest" 

    collected_data = []
    time_of_collection = datetime.utcnow().isoformat() # timestamp of when data is collected

    for station in WEATHER_STATIONS:
        url = BASE_URL.format(station=station)
        response = requests.get(url) # send api request
        if response.status_code == 200:
            props = response.json().get("properties", {}) # extract data
            collected_data.append({
                "timeOfCollection": time_of_collection,
                "timestamp": props.get("timestamp"),
                "station": station,
                "temperature": props.get("temperature", {}).get("value"),
                "dewpoint": props.get("dewpoint", {}).get("value"),
                "windSpeed": props.get("windSpeed", {}).get("value"),
                "barometricPressure": props.get("barometricPressure", {}).get("value"),
                "visibility": props.get("visibility", {}).get("value"),
                "precipitationLastHour": props.get("precipitationLastHour", {}).get("value"),
                "relativeHumidity": props.get("relativeHumidity", {}).get("value"),
                "heatIndex": props.get("heatIndex", {}).get("value"),
            })
        else:
            print(f"Failed to fetch data for {station}")
        time.sleep(2) # sleep to avoid hitting rate limit

# Converting to df and uploading to s3
    df = pd.DataFrame(collected_data)
    timestamp_str = datetime.utcnow().strftime('%Y%m%d_%H%M%S') # current time for filename
    s3_key = f"{S3_DATA_DIR}weather_obs_{timestamp_str}.csv" # full s3 key
    upload_to_s3(df, s3_key) # uploading


# Defining DAG config
default_args = {
    'owner': 'natarajan_williams_silverman',
    'depends_on_past': False,
    'start_date': pendulum.today('UTC').add(days=-1),
    'end_date': pendulum.today('UTC').add(days=1),
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

# Defining DAG and task
dag = DAG(
    'weather_data_pipeline',
    default_args=default_args,
    description='Collect weather data and upload to S3 every 2 hours',
    schedule='0 */2 * * *', # every 2 hours
    tags=['weather', 's3'],
)

collect_task = PythonOperator(
    task_id='collect_weather_data',
    python_callable=collect_weather_data,
    dag=dag,
)
