# -*- coding: utf-8 -*-
"""weather_lin_reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIggFrEi6YODnawtdkGKWnMMjmTqqqC5
"""
# Importing
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.exceptions import AirflowSkipException
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import boto3
import io
import pendulum
from sklearn.linear_model import LinearRegression


# AWS configuration
BUCKET_NAME = "natarajan-williams-silverman-bucket"
S3_DATA_DIR = "weather_data/" # input location
S3_OUTPUT_DIR = "predictions/" # output location (where predictions go)
AWS_REGION = "us-east-2"

session = boto3.Session(region_name=AWS_REGION)
s3 = session.client("s3")

# Training and predicting future temperatures (task)
def train_and_predict(**kwargs):
    response = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix=S3_DATA_DIR)
    files = [obj["Key"] for obj in response.get("Contents", []) if obj["Key"].endswith(".csv")]
    if not files:
        print("No weather data files found.")
        return
    # Loading CSVs into a single DF
    dfs = []
    for file_key in files:
        obj = s3.get_object(Bucket=BUCKET_NAME, Key=file_key)
        df = pd.read_csv(io.BytesIO(obj["Body"].read()))
        dfs.append(df)

    df_all = pd.concat(dfs, ignore_index=True)
    df_all.dropna(subset=["timestamp", "temperature", "station"], inplace=True)
    df_all["timestamp"] = pd.to_datetime(df_all["timestamp"])

    # Checking if data spans required range (20 or 40 hrs)
    min_time = df_all["timestamp"].min()
    max_time = df_all["timestamp"].max()
    elapsed_data_hours = (max_time - min_time).total_seconds() / 3600
    print(f"Data covers {elapsed_data_hours:.2f} hours")

    # Only run if data spans 20 or 40 hours
    if not (19 <= elapsed_data_hours < 22 or 39 <= elapsed_data_hours < 42):
        raise AirflowSkipException(f"Data does not align with 20h or 40h milestone (currently {elapsed_data_hours:.2f}h)")

    # Preparing features and training the model
    df_all["hour"] = df_all["timestamp"].dt.hour
    df_all["minute"] = df_all["timestamp"].dt.minute
    df_all["station_cat"] = df_all["station"].astype("category").cat.codes

    feature_cols = [
        "dewpoint", "windSpeed", "barometricPressure", "visibility",
        "precipitationLastHour", "relativeHumidity", "heatIndex",
        "hour", "minute", "station_cat"
    ]

    for col in feature_cols:
        mean_val = df_all[col].mean()
        fill_val = 0.0 if pd.isna(mean_val) else mean_val
        df_all[col] = df_all[col].fillna(fill_val)

    X = df_all[feature_cols]
    y = df_all["temperature"]

    model = LinearRegression()
    model.fit(X, y)


    # Generating future timestamps and predicting
    now = datetime.utcnow()
    future_steps = pd.date_range(now, periods=16, freq='30min')

    preds = []
    for station in df_all["station"].unique():
        code = df_all[df_all["station"] == station]["station_cat"].iloc[0]
        for t in future_steps:
            row = {
                "dewpoint": df_all["dewpoint"].mean(),
                "windSpeed": df_all["windSpeed"].mean(),
                "barometricPressure": df_all["barometricPressure"].mean(),
                "visibility": df_all["visibility"].mean(),
                "precipitationLastHour": df_all["precipitationLastHour"].mean(),
                "relativeHumidity": df_all["relativeHumidity"].mean(),
                "heatIndex": df_all["heatIndex"].mean(),
                "hour": t.hour,
                "minute": t.minute,
                "station_cat": code
            }
            x_input = pd.DataFrame([row])
            temp_pred = model.predict(x_input)[0]
            row.update({
                "station": station,
                "forecast_time": t.isoformat(),
                "predicted_temperature": temp_pred
            })
            preds.append(row)


    # Uploading predictions
    df_preds = pd.DataFrame(preds)
    timestamp_str = datetime.utcnow().strftime("%Y-%m-%dT%H-%M-%S")
    file_name = f"{S3_OUTPUT_DIR}temp_predictions_{timestamp_str}.csv"
    buffer = io.StringIO()
    df_preds.to_csv(buffer, index=False)
    s3.put_object(Bucket=BUCKET_NAME, Key=file_name, Body=buffer.getvalue())
    print(f"Predictions saved to s3://{BUCKET_NAME}/{file_name}")


# Setting up the DAG
default_args = {
    'owner': 'natarajan_williams_silverman',
    'depends_on_past': False,
    'start_date': pendulum.datetime(2025, 6, 2, tz="UTC"),
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'weather_regression_dag',
    default_args=default_args,
    description='Train and predict temperature after 20 and 40 hours using existing weather data in S3',
    schedule='0 * * * *',
    catchup=True,
    tags=["weather", "regression"]
)

train_predict_task = PythonOperator(
    task_id='train_and_predict_temperature',
    python_callable=train_and_predict,
    dag=dag,
)
